fix bugs
ipc2023-learning/repo05 pull request #1
Opened 2023-05-30 05:33 UTC by u6684258

Three main changes:
1. update the tokeniser to the latest version to support necessary PDDL keywords;
2. update the fast-downward API as some function names have changed in the latest version (planner methodology not changed)
3. update the singularity file for bug fixing

2023-05-30 19:16 UTC, jendrikseipp requested changes

2023-05-30 19:16 UTC, jendrikseipp commented on Apptainer.asnets.plan
> +    pip3 install wheel cython numpy pkgconfig werkzeug urllib3==1.26.15
Can you please pin the versions of the other Python packages on this line? This ensures that the code works in the future as well.

2023-05-30 19:16 UTC, jendrikseipp commented on Apptainer.asnets.learn
> +    pip3 install wheel cython numpy pkgconfig werkzeug urllib3==1.26.15
Please specify the versions of the other packages on this line as well.

2023-05-30 19:16 UTC, jendrikseipp commented on asnets/asnets/interfaces/fd_interface.py
> +            ("hlm=landmark_sum(lm_factory=lm_rhw(),"
```suggestion
            ("hlm=landmark_sum(lm_factory=lm_reasonable_orders_hps(lm_rhw()),"
```
This preserves the reasonable_orders=true flag. Please check that the planner call still works.

2023-06-01 05:25 UTC, u6684258 commented on asnets/asnets/interfaces/fd_interface.py
> +            ("hlm=landmark_sum(lm_factory=lm_rhw(),"
Thanks for the suggestion : )

2023-06-01 07:22 UTC, merged